overhaul format script

diff --git a/format b/format
--- a/format
+++ b/format
@@ -1,46 +1,148 @@
-#!/bin/sh
-set -ux
+#!/bin/bash
+set -Eeuo pipefail
+trap 'echo "$0: Error on line ${LINENO}: ${BASH_COMMAND}" >&2' ERR
 
-dev="$1"
-mnt="mnt"
+EFI_LABEL=GHOUL-EFI
+BOOT_LABEL=ghoul-boot
+DATA_LABEL=ghoul-data
 
-[ -z "$dev" ] && exit 1
+HYBRID=true
+FORMAT=true
 
-sgdisk --zap-all "$dev"
-sgdisk \
-	--new=1:0:+64M --typecode=0:ef00 \
-	--new=2:0:-16G --typecode=0:8300 \
-	--new=3:0:0 --typecode=0:0700 \
-	--new=4:34:0 --typecode=0:ef02 \
-	--hybrid 1:2:3:EE \
-	"$dev"
+usage() {
+	echo "Usage: $0 [--gpt-only] [--skip-format] <dev>" >&2
+}
 
-mkfs.fat -F32 -n usb-efi "${dev}1"
-mkfs.ext4 -L usb-boot "${dev}2"
-mkfs.exfat -L usb-data "${dev}3"
+if ! OPTS=$(getopt -o '' --longoptions 'gpt-only,skip-format' -- "$@"); then
+	usage
+	exit 1
+fi
 
-mkdir "$mnt"
-mount "${dev}2" "$mnt"
+eval set -- "$OPTS"
+unset OPTS
 
-	mkdir "${mnt}/boot"
-	mkdir "${mnt}/efi"
-	mount "${dev}1" "${mnt}/efi"
+while true; do
+	case "$1" in
+	--gpt-only)
+		HYBRID=false
+		shift
+		;;
+	--skip-format)
+		FORMAT=false
+		shift
+		;;
+	--)
+		shift
+		break
+		;;
+	*)
+		if [ -n "$1" ]; then
+			echo "Error: Unrecognized option ${1}" >&2
+		fi
+		exit 1
+		;;
+	esac
+done
 
-	grub-install \
-		--target=x86_64-efi \
-		--recheck \
-		--removable \
-		--efi-directory="${mnt}/efi" \
-		--boot-directory="${mnt}/boot"
+if [ $# -ne 1 ]; then
+	usage
+	exit 1
+fi
 
+DEV="$1"
+if [ ! -b "$DEV" ]; then
+	echo "Error: '$DEV' is not a block device" >&2
+	exit 1
+fi
+
+require_command() {
+	if ! command -v -- "$1" >/dev/null; then
+		echo "Error: '$1' command not found. Please install the package that provides '$1'" >&2
+		exit 1
+	fi
+}
+if [ "${FORMAT}" = true ]; then
+	require_command sgdisk
+	require_command mkfs.fat
+	require_command mkfs.ext4
+	require_command mkfs.exfat
+fi
+require_command grub-install
+require_command rsync
+
+MNT="$(mktemp --directory -t ghoul-mnt.XXXX)"
+cleanup() {
+	if mountpoint -q "${MNT}"; then
+		echo 'Unmounting...'
+		umount -R "${MNT}"
+	fi
+	rmdir "$MNT"
+}
+trap cleanup EXIT
+
+if [ "${FORMAT}" = true ]; then
+	yn() {
+		while :; do
+			printf '%s [%s/%s] ' "$1" "$(locale yesstr)" "$(locale nostr)"
+			read -r 'response'
+			printf '%s' "${response}" | grep -Eq "$(locale yesexpr)" && return 0
+			printf '%s' "${response}" | grep -Eq "$(locale noexpr)" && return 1
+		done
+	}
+	yn "This will wipe all data in '$DEV'. Continue?" || exit 0
+
+	echo 'Zapping all partitioning data...'
+	sgdisk --zap-all "$DEV"
+
+	echo 'Partitioning...'
+	sgdisk \
+		--new=1:0:+64M --typecode=0:ef00 \
+		--new=2:0:-16G --typecode=0:8300 \
+		--new=3:0:0 --typecode=0:0700 \
+		"${DEV}"
+
+	if [ "${HYBRID}" = true ]; then
+		echo 'Making partitioning hybrid...'
+		sgdisk \
+			--new=4:34:0 --typecode=0:ef02 \
+			--hybrid 1:2:3:EE \
+			"${DEV}"
+	fi
+
+	echo 'Formatting EFI partition...'
+	mkfs.fat -F32 -n "${EFI_LABEL}" "${DEV}1"
+	echo 'Formatting BOOT partition...'
+	mkfs.ext4 -L "${BOOT_LABEL}" "${DEV}2"
+	echo 'Formatting DATA partition...'
+	mkfs.exfat -L "${DATA_LABEL}" "${DEV}3"
+fi
+
+echo 'Mounting...'
+mount -L "${BOOT_LABEL}" "${MNT}"
+mkdir --parent "${MNT}/boot"
+mkdir --parent "${MNT}/efi"
+
+mount -L "${EFI_LABEL}" "${MNT}/efi"
+
+echo 'Installing GPT GRUB...'
+grub-install \
+	--target=x86_64-efi \
+	--recheck \
+	--removable \
+	--efi-directory="${MNT}/efi" \
+	--boot-directory="${MNT}/boot"
+
+if [ "${HYBRID}" = true ]; then
+	echo 'Installing MBR GRUB...'
 	grub-install \
 		--target=i386-pc \
 		--recheck \
-		--boot-directory="${mnt}/boot" \
-		"${dev}"
+		--boot-directory="${MNT}/boot" \
+		"${DEV}"
+fi
 
-cp -r glim/grub2/. mnt/boot/grub
-cp -r iso mnt/boot
+echo 'Copying grub configuration files...'
+rsync --progress --recursive glim/grub2/. "${MNT}/boot/grub"
 
-umount -R "$mnt"
-rmdir "$mnt"
+echo 'Copying iso files...'
+rsync --progress --recursive iso "${MNT}/boot"
